### ISSUE TITLE
Retarded output

### ISSUE THREAD

**Issue by Vlek** [kelvv/regexper.js#1]
Why can't the matches just output an array of strings which matched the search criteria? I don't think there's any outweighing benefit to having to iterate over the returned object to pull all of the strings out of insanely nested object/arrays for the information that the person is most likely attempting to get.

**Comment by kelvv** [comment]
@Vlek  Thank you for the feedback!

the matches meth will return an array of object :

match : {
              value : string
              index : number,
              groups: [{
                value : string
              }]
}

so i think this is simple enough , Any Suggestions?

**Comment by Vlek** [comment]
Honestly, I can't tell how that's any different than the stupid crap it's doing now.

Here's what's currently going on:
```
var Regex = require('regexper.js');

var str = 'One fish, two fish, red fish, blue fish!';
var regex = new Regex(/(.*?) fish/, 'g');

var matches = regex.matches(str);

// We shouldn't have to do any of this to get out the groups, but here we are.
var fishnames= [];
for (var m in matches){
    fishnames.push(matches[m].groups[0].value);
}

console.log(fishnames); // -> [ 'One', 'two', 'red', 'blue' ]
```

What you'd expect in a sane world to happen is this:

```
var str = 'One fish, two fish, red fish, blue fish!';
var regex = new Regex(/(.*?) fish/, 'g');

var matches = regex.matches(str);

console.log(matches); // -> [ 'One', 'two', 'red', 'blue' ]
```

Hell, I'd even settle for this:

```
var str = 'One fish, two fish, red fish, blue fish!';
var regex = new Regex(/(.*?) fish/, 'g');

var matches = regex.matches(str);

console.log(matches.groups); // -> [ 'One', 'two', 'red', 'blue' ]
```

I guess the path of least resistance you could use is to have groups NOT an array of objects, but an array of the strings that matched:

```
match : {
    value : string
    index : number,
    groups: [string]
}
```

It's just absolutely insane to have to iterate through again for no added benefit.

**Comment by kelvv** [comment]
Thank you for your suggestion,

There are somthing i want to show you :

`
var Regex = require('regexper.js');

var str = 'One 1 fish, two 2 fish, red 3 fish, blue 4 fish!';
var regex = new Regex(/(\w+) (\d+) fish/, 'g');

var matches = regex.matches(str);

var fishnames= [];
for (var match of matches){
    fishnames.push(match.groups[0].value);
    fishnames.push(match.groups[1].value);
}

console.log(fishnames); // -> [ 'One' , '1' , 'two' ,  '2' , 'red' , '3' , 'blue' ,'4']
`

This is why 'match.groups' should be an array of object

**Comment by kelvv** [comment]
it is good to use :

```
match : {
    value : string
    index : number,
    groups: [string]
}
```

**Comment by Vlek** [comment]
There's a serious language barrier problem here, so I don't think you're quite getting it. When you do matches, you wouldn't expect to have to iterate over anything to get the groups out. Either rate, I decided to use the basic regular expressions in javascript, so goodluck with your project.

**Comment by kelvv** [comment]
@Vlek Hello , new version v1.0.6 is published 

match : {
    value : string
    index : number,
    groups: [string]
}

thank you
